import "../styles/global.css";

export const metadata = {
  title: "blog app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body> {children}</body>
    </html>
  );
}
